{
    "steps":
        [
            {
                "name": "gcr.io/cloud-builders/docker",
                "args":
                    ["build", "-t", "gcr.io/see_you_letter/helloworld", "."],
            },
            {
                "name": "gcr.io/cloud-builders/docker",
                "args": ["push", "gcr.io/see_you_letter/helloworld"],
            },
            {
                "name": "gcr.io/cloud-builders/gcloud",
                "args":
                    [
                        "run",
                        "deploy",
                        "helloworld2",
                        "--image",
                        "gcr.io/see_you_letter/helloworld",
                        "--region",
                        "asia-northeast1",
                        "--platform",
                        "managed",
                        "--allow-unauthenticated",
                    ],
            },
        ],
}
